ChainSafe/ssz

- src/backings/tree/array.ts
- src/backings/tree/bitList.ts
- src/backings/tree/bitVector.ts
There were a few places where tree memory was being mutated.
This leads to cases where eg: a zeroNode gets overwritten.
> Fix accidental memory overwrites

- src/util/merkleize.ts
- src/util/zeros.ts
A previous commit changed our `hash` implementation from `hash(Buffer) => Buffer` to `hash(Uint8Array) => Uint8Array`
This caused a few type errors that are cleaned up here.
> Fix type errors

- src/types/basic/uint.ts
- test/unit/regression.test.ts
I realize we will also have issue because we serialize FAR_FUTURE_EPOCH as "Infinity" while other clients uses number defined in [spec](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#constants).
> Fix far future deserialization

- src/types/basic/abstract.ts
- src/types/basic/boolean.ts
- src/types/basic/uint.ts
- src/types/composite/abstract.ts
- src/types/composite/bitList.ts
- src/types/composite/bitVector.ts
- src/types/composite/byteVector.ts
- src/types/composite/container.ts
- src/types/composite/list.ts
- src/types/composite/root.ts
- src/types/composite/vector.ts
- test/unit/isFooType.test.ts
Adds the following exported functions:
- `isUintType`
- `isNumberUintType`
- `isBigIntUintType`
- `isBooleanType`
- `isListType`
- `isVectorType`
- `isBitListType`
- `isBitVectorType`
- `isByteVectorType`
- `isContainerType`
- `isRootType`
> Add isFooType functions

- src/backings/index.ts
- src/backings/object.ts
Add `ObjBacked` wrapper type to explicitly cast an ssz object to be backed by built-in javascript objects.
```typescript
// so we already have this
const b: TreeBacked<BeaconBlock> = ...;
b.body.voluntaryExits // type of List<VoluntaryExit>
b.body.randaoReveal // type of ByteVector
// adding this
const b: ObjBacked<BeaconBlock> = ...;
b.body.voluntaryExits // type of VoluntaryExit[]
b.body.randaoReveal // type of Uint8Array
```
> Add ObjBacked wrapper type

- src/types/basic/uint.ts
In `NumberUintType#toBytes`, instead of `BigInt` bitshifting, use `Math.floor`'d `number` division.
This allows environments which don't support `BigInt` to `hashTreeRoot` js objects.
> Don't use BigInt in NumberUintType#toBytes

- src/types/basic/uint.ts
resolve https://github.com/ChainSafe/ssz/issues/34
current approach:
for `uint8`, `uint16`, `uint32`, `toJson` returns a `number`, else (`uint48` and higher) returns a `string`
an alternative approach could be:
for every `uint`, `toJson` returns a `string` (no matter the bit/bytelength)
> Standardize uint toJson

- test/unit/clone.test.ts
- test/unit/defaultValue.test.ts
- test/unit/deserialize.test.ts
- test/unit/equals.test.ts
- test/unit/hashTreeRoot.test.ts
- test/unit/serialize.test.ts
In test logs print
```
should correctly serialize ByteVectorType
```
instead of 
```
should correctly serialize [object Object]
```
> Print type name in test declaration

- test/unit/errors.test.ts
As recommended by @mpetrunic the case is skipped until the implementation to catch the error is done.
> Add deserialization case that should throw an Error

- src/backings/structural/abstract.ts
Start param should error if it is `>` data.length, not `>=`.
> Fix start param validation case

- src/backings/structural/bitList.ts
- test/unit/errors.test.ts
See https://discordapp.com/channels/593655374469660673/593655641445367808/730567234719842345
Included testcase, fails before, success now.
The `chunk` method is used in the structural backing case to retrieve the merkle "chunk" at a certain chunk index.
In the bitlist/bitvector structural code, we mistakenly assume the `index` is the byte index, rather than the chunk index.
> Fix structural bitlist/bitvector hashtreeroot

- src/backings/structural/list.ts
- src/backings/structural/vector.ts
Due to https://github.com/ChainSafe/ssz/issues/49 we missed several issues that resulted in spec test failures.
This resolves the immediate issue, namely the validation for bitlist/bitvector incorrectly assumed the bytelength of the serialized form based on the `size` of the array's elementType. In the bitlist/bitvector case, the elementType is a BooleanType, with size of 1 (byte), wheras in bitlists, booleans are treated specially, and bitpacked.
> Fix bitlist/bitvector validation

- package.json
- src/backings/index.ts
- src/backings/readOnlyIterate.ts
- src/backings/tree/abstract.ts
- src/backings/tree/array.ts
- src/backings/tree/bitList.ts
- src/backings/tree/bitVector.ts
- src/backings/tree/container.ts
- yarn.lock
Depends on chainsafe/persistent-merkle-tree#13 and subsequent release
- Update persistent-merkle-tree usage (`toGindex`, `iterateAtDepth` param order change)
- Use `Tree#iterateNodesAtDepth` in tree-backing `toBytes`
- Add `readOnlyForEach` and `readOnlyMap` methods and helper functions
> read-only tree iteration

- package.json
- src/backings/tree/array.ts
- src/backings/tree/container.ts
- src/backings/tree/list.ts
- yarn.lock
~Depends on https://github.com/ChainSafe/persistent-merkle-tree/pull/15 and subsequent release~
`fromStructural` is the method to convert structural objects to tree objects
Previously, `fromStructural` has the following strategy:
- create a default tree, loop thru the structural values, setting each sub-value to each place in the tree
Now:
- loop thru the structural values, creating an array of leaf nodes, create a tree from the leaf nodes
This new approach is significantly faster, as it avoids navigation thru the tree + rebinding nodes for each sub-value.
> Optimize fromStructural, use subtreeFillToContents

- src/backings/readOnlyIterate.ts
- src/backings/tree/container.ts
Iterate at depth through a container, expose an `Object.entries`-like interface.
> Add readOnlyEntries

- src/backings/tree/abstract.ts
- src/backings/tree/array.ts
- src/backings/tree/bitList.ts
- src/backings/tree/bitVector.ts
- src/backings/tree/container.ts
BREAKING CHANGE:
TreeBacked<T>#gindexOfProperty is removed in favor of
TreeHandler#gindexOfProperty
`gindexOfProperty(target: Tree, property: PropertyKey): Gindex` => 
`gindexOfProperty(property: PropertyKey): Gindex`
Calculating gindices shouldn't rely on the value (the actual tree), since no calculations actually rely on the value.
Instead, just the type information alone is enough to calculate gindices.
Consumers previously using the public method should upgrade like so:
```ts
const value: TreeBacked<T> = ...;
// before
value.gindexOfProperty('foo')
// after
value.type().gindexOfProperty('foo')
```
The gindexOfProperty is very "low level" and likely only needed for proof generation machinery.
In the future, proof generation methods may be added to TreeBacked<T> to provide convenience.
> Remove TreeBacked<T>#gindexOfProperty

- src/backings/structural/container.ts
- src/backings/tree/container.ts
- src/types/basic/abstract.ts
- src/types/basic/boolean.ts
- src/types/basic/uint.ts
- src/types/composite/abstract.ts
- src/types/composite/array.ts
- src/types/composite/bitList.ts
- src/types/composite/bitVector.ts
- src/types/composite/byteVector.ts
- src/types/composite/container.ts
- src/types/composite/list.ts
- src/types/composite/root.ts
- src/types/composite/vector.ts
- src/types/type.ts
BREAKING CHANGE:
Remove Type#isBasic in favor of isBasicType function
- Make `Type` an abstract class (rather than a type)
- Make `BasicType`, `CompositeType`, , `UintType`, `BasicArrayType`, `CompositeArrayType` abstract
- `Type#isBasic` now no longer works as intended (to coerce the type to a `CompositeType`), so remove it, use `isBasicType`/`isCompositeType` instead
Any consumers that previously used `Type#isBasic` can now use either `isBasicType` or `isCompositeType`
```ts
const t: Type<unknown> = ...;
// before
if (t.isBasic()) {
...
} else {
// t is a CompositeType
t.tree.defaultValue();
}
// after
if (!isCompositeType(t)) {
...
} else {
// t is a CompositeType
t.tree.defaultValue();
}
```
> Use abstract class Type/BasicType/CompositeType

- package.json
- src/types/basic/uint.ts
- test/perf/deserialize.test.ts
- test/perf/objects.ts
- test/perf/serialize.test.ts
resolves #71
+ process Uint types by a group of 4 bytes (which supports shift operators for number), so we only use BigInt once per 4 bytes (25% compared to the current implementation)
+ Added performance tests
|test|minTime|averageTime|maxTime|
|----|--------|-------------|---------|
|master - serialize|228|262|745|
|this branch - serialize|90|100|480|
|master - deserialize|241|278|663|
|this branch - deserialize|85|100|320|
|master - readOnlyMap perf test|141|173|636|
|this branch - readOnlyMap perf test|39|55|262|
+ passed `test:ssz` and `test:ssz-min` spec tests in lodestar
> Restrict the use of BigInt whenever possible

- src/types/basic/uint.ts
- test/perf/deserialize.test.ts
- test/perf/fromStructural.test.ts
- test/perf/objects.ts
- test/perf/serialize.test.ts
resolves #77 
+ Switch back to use number bit shifting to improve performance. Added `fromStructural.test.ts` to prove that and for other improvements in the future if any
+ Leverage `BigInt.asUintN` api and added `BIGINT_4_BYTES` constant to reduce BigInt allocation
Performance statistics for `fromStructural` test:
|Branch|minTime (ms)|maxTime (ms)|average (ms)|
|-------|--------------|--------------|-------------|
|master - 1st|105|678|124.9|
|master - 2nd|104|583|119.32|
|this PR - 1st|62|322|78.00|
|this PR - 2nd|64|376|78.61|
> Improve BigIntUintType.toBytes() to use number bitshifting

- src/types/composite/abstract.ts
This was lost between 0.7.x and 0.8.0
> Add tree_createFromProof

- src/util/byteArray.ts
- test/unit/hexString.test.ts
See https://github.com/ChainSafe/ssz/issues/100 hexToString() is an significant performance bottleneck.
Replaced the toHexString and fromHexString for simpler alternatives that are
toHexString: x12 faster (now 0.4 µs / op, 32 bytes input)
fromHexString: x2 faster (now 2.4 µs / op, 32 bytes input)
Closes https://github.com/ChainSafe/ssz/issues/100
> Improve hexToString performance

- src/types/composite/abstract.ts
- src/types/composite/array.ts
- src/types/composite/container.ts
- src/types/composite/list.ts
- test/unit/proof.test.ts
When creating a proof with a path to a composite type, include all
leaves of the type in the proof.
- Add `CompositeType#tree_getLeafGindices(tree?: Tree, root?: Gindex): Gindex[]`
- This is where the magic happens. Composite types are recursively traversed to the terminal types to get leaf gindices.
- The tree is included for 'length' information for variable-length objects. (otherwise we wouldn't know which gindices to include for eg: `state.validators`)
- A "root" gindex is included to allow for deeply nested types to return gindices relative to the root type
- `CompositeType#createProof` is extended to call `tree_getLeafGindices` when the type at a path is a composite type.
> Add composite type leaves to proof

- src/types/composite/bitVector.ts
- test/unit/regression.test.ts
+ `BitVector.tree_deserializeFromBytes` has a check to make sure all bits after `length` should be 0, but that should only be for the case vector does not take up the whole byte
+ close #115
> Fix BitVector tree_deserializeFromBytes()

- .github/workflows/benchmark.yml
```
Error: auto-push must be false when external-data-json-path is set since this action reads/writes the given JSON file and never pushes to remote
```
> Fix benchmark action

- test/perf/utils/runner.ts
```
Error: No benchmark result was found in /home/runner/work/ssz/ssz/benchmark-output.txt. Benchmark output was 'Simple object binary -> struct x 223264.12145568206 ±0.00% (19164 runs sampled)
```
> Fix benchmark output formatting

- src/types/composite/bitList.ts
- src/types/composite/bitVector.ts
- test/unit/regression.test.ts
Close #123 
+ `BitVectorType.struct_getRootAtChunkIndex` accepts a chunk index, not byte index so we have to multiply 32 as byte offset
+ Rename variables accordingly and add unit test
> Fix struct_getRootAtChunkIndex for BitVectorType

- src/types/composite/bitList.ts
Tested against generic and static ssz spec tests
> Fix tree_serializeToBytes offset in BitList

- src/types/basic/uint.ts
- src/util/bigInt.ts
- test/unit/util.test.ts
Downstream libraries may transpile this library to remove the exponentiaiton (`**`) operator.
In the case of exponentiating bigints, the code gets incorrectly transpiled from `BigInt(a) ** BigInt(b)` to `Math.pow(BigInt(a), BigInt(b))`
This PR avoids using `**` with bigints by replacing it with a utility function that does the same.
> Use utility function for bigint exponentiation

- src/types/basic/abstract.ts
- src/types/composite/abstract.ts
- src/types/composite/array.ts
- src/types/composite/bitVector.ts
- src/types/composite/container.ts
- src/types/composite/list.ts
- src/types/composite/vector.ts
- src/types/type.ts
In ssz lib there's a bad type pattern used in
```ts
this.elementType.struct_getSerializedLength(null)
```
since getSerializedLength may or may not require an argument depending on if it is variable length or not.
```ts
if (this.elementType.hasVariableSerializedLength()) {
// variable stuff
} else {
return this.elementType.struct_getSerializedLength(null);
}
```
A more typesafe pattern, which requires one less call is
```ts
const fixedLen = this.elementType.getFixedSerializedLength()
if (fixedLen === null) {
// variable stuff
} else {
return fixedLen
}
```
where it uses type information to figure out if it's variable length or not.
----
@wemeetagain please review I didn't messed up any of the logic
> Add getFixedSerializedLength()

- package.json
- src/types/composite/list.ts
- test/perf/list.test.ts
- test/unit/tree.test.ts
- yarn.lock
**Motivation**
+ Right now to apply a delta, we have to traverse the tree to get HashObject, calculate new HashObject and set it back at same gindex. It's better if we could traverse the tree only 1 time
+ Use the new `setHashObjectFn()` of persistent-merkle-tree
+ Waiting for https://github.com/ChainSafe/persistent-merkle-tree/pull/62 https://github.com/ChainSafe/ssz/pull/159
> Traverse the tree only 1 time for applyDelta flow

- package.json
- src/types/composite/abstract.ts
- src/types/composite/array.ts
- src/types/composite/bitList.ts
- src/types/composite/bitVector.ts
- src/types/composite/container.ts
- src/types/composite/union.ts
- yarn.lock
**Motivation**
+ Minor improvement: we want to use `GIndexBitString` whenever possible to avoid BigInt allocation.
+ This depends on https://github.com/ChainSafe/persistent-merkle-tree/pull/45
> Use gindexbitstring whenever possible

- src/backings/tree/treeValue.ts
- src/types/composite/containerLeafNodeStruct.ts
- test/unit/validators.test.ts
With current master the validator object is returned as `ContainerTreeValue`. However since it's not really tree backed acessing it's properties errors with 
```
1) Container with BranchNodeStruct
ValidatorLeafNodeStructType in List
Should return pubkey as struct backed:
TypeError: target.getNodesAtDepth is not a function
at ByteVectorType.tree_convertToStruct (src/types/composite/byteVector.ts:59:27)
at Proxy.valueOf (src/backings/tree/treeValue.ts:125:22)
at Context.<anonymous> (test/unit/validators.test.ts:127:52)
at processImmediate (internal/timers.js:464:21)
```
This PR makes createTreeBacked return a TreeValue that can deal with LeafNodeStruct nodes
> Fix ContainerLeafNodeStructTreeValue

- packages/ssz/src/types/composite/container.ts
- packages/ssz/src/types/type.ts
- packages/ssz/src/util/json.ts
- packages/ssz/test/unit/json.test.ts
- packages/ssz/test/unit/objects.ts
extending the case transformation to other cases available in the "case" library in container data fill plus adding a `notransform` option and making no transformation default
plus test case for `notranform`
> extending the case transformation in container data fill

- .github/workflows/release.yml
**Motivation**
reverting the changes made to release.yml  in favour of  lerna publish based release workflow which seems to be tagging, creating reease, changelog as well apart from publishing to the npm repos.
This workflow has been tested in the @g11tech/ssz forked repo using `lerna publish patch --yes --no-verify-access --skip-npm` publish command instead of the original `lerna publish from-package --yes --no-verify-access` for testing all aspects of the workflow (except fetching versions and deploying to npm)
attached is the successful run in the forked repo:
#203
> lerna publish based release workflow

- packages/persistent-ts/src/Vector.ts
**Motivation**
We don't want to use closures for the performance reason
part of https://github.com/ChainSafe/lodestar/issues/3267
> Remove iterateNodeValues closure

- packages/ssz/test/memory/bytes.test.ts
- packages/ssz/test/memory/eth2Objects.test.ts
- packages/ssz/test/memory/testRunnerMemory.ts
- packages/ssz/test/memory/treeView.test.ts
- packages/ssz/test/perf/deserializationEth2.test.ts
- packages/ssz/test/utils/generateEth2Objs.ts
**Motivation**
Get data on the memory cost of various data structures relevant to SSZ and Lodestar.
This benchmarks have been run in a Linux laptop, Max OS laptop and Linux VPS getting almost exact results. So the method `testRunnerMemory()` appears to be very reliably for not huge objects. Once we want to measure the whole beacon state, it will need a different strategy.
Benchmark memory of various SSZ and Lodestar data structures
> Benchmark memory

- packages/simpleserialize.com/src/components/worker/helpers.ts
**Motivation**
Issue introduced in #223
> Fix createRandomValue

- packages/ssz/test/unit/byType/byteList/valid.test.ts
**Motivation**
From issue https://github.com/ChainSafe/lodestar/issues/3896 there is an serialization issue, not covered by any unit test.
- Test empty ByteListType
> Test empty ByteListType

- packages/ssz/src/type/abstract.ts
- packages/ssz/src/type/bitList.ts
- packages/ssz/src/type/bitVector.ts
- packages/ssz/src/type/byteArray.ts
- packages/ssz/src/type/byteList.ts
- packages/ssz/src/type/byteVector.ts
- packages/ssz/src/value/bitArray.ts
- packages/ssz/test/perf/uintFromBytes.test.ts
- packages/ssz/test/spec/runValidTest.ts
- packages/ssz/test/unit/uint8Array.test.ts
**Motivation**
SSZ expected that all arguments typed as `Uint8Array` as `Uin8Array` but they could get a `Buffer` instance too.
Buffer.prototype.slice does not copy memory, force use Uint8Array.prototype.slice https://github.com/nodejs/node/issues/28087
- Uint8Array.prototype.slice: Copy memory, safe to mutate
- Buffer.prototype.slice: Does NOT copy memory, mutation affects both views
We could ensure that all Buffer instances are converted to Uint8Array before calling value_deserializeFromBytes. However doing that in a browser friendly way is not easy. Downstream code uses `Uint8Array.prototype.slice.call` to ensure Buffer.prototype.slice is never used. Unit tests also test non-mutability.
Use `Uint8Array.prototype.slice` to ensure the method that copies memory is used. …
> Force usage of Uint8Array.prototype.slice

- packages/simpleserialize.com/CHANGELOG.md
- packages/simpleserialize.com/package.json
- yarn.lock
**Motivation**
The ssz types in simple serialize are old and error on bellatrix execution types (raised on chainsafe discord ssz troubleshooting)
this push updates the ssz and types package to latest and should resolve issues.
> update and publish simpleserialize.com

- packages/persistent-merkle-tree/src/proof/efMulti.ts
- packages/persistent-merkle-tree/src/proof/index.ts
- packages/persistent-merkle-tree/src/proof/multi.ts
- packages/persistent-merkle-tree/src/proof/single.ts
- packages/persistent-merkle-tree/src/proof/util.ts
- packages/persistent-merkle-tree/test/unit/proof/index.test.ts
- packages/persistent-merkle-tree/test/unit/proof/util.test.ts
**Motivation**
We need to support the multiproof format described in the consensus specs repo:
https://github.com/ethereum/consensus-specs/blob/dev/ssz/merkle-proofs.md
Bare minimum to support EF multiproofs
TODO:
> Add EF multiproof format

- packages/persistent-merkle-tree/src/tree.ts
- packages/ssz/src/viewDU/listComposite.ts
- packages/ssz/test/unit/byType/listComposite/tree.test.ts
**Motivation**
`ListCompositeType.sliceTo(-1)` should return an empty list as it means "set all positive indexes to 0".
The root cause is that `treeZeroAfterIndex` function returns incorrect results if index is less than zero.
Add early return in `treeZeroAfterIndex`. All positive indexes are zero, so the entire tree is zero. Return cached zero node as root.
> Fix ListCompositeType.sliceTo(-1)

- packages/ssz/src/type/uint.ts
**Motivation**
named static fn for UintBigintType uses the wrong union
- Fix typo in UintBigintByteLen
> Fix typo in UintBigintByteLen

- packages/ssz/package.json
- packages/ssz/src/type/container.ts
- packages/ssz/src/util/strings.ts
- packages/ssz/test/unit/strings.test.ts
**Motivation**
Removes an external dependency, thus removing the surface area for supply chain atttacks.
Replaces `case` dependency that's only used for string manipulation with an internal helper method that accomplishes the same goal.
Run impacted tests.
```sh
cd packages/ssz
npx mocha -- "test/unit/eth2/caseEth2.test.ts" "test/unit/strings.test.ts"
```
> feat: Switch case dependency to internal helper

- .github/workflows/cd.yml
**Motivation**
We want the release-please PR to trigger workflows
Use a different secret for release-please
See https://github.com/google-github-actions/release-please-action#github-credentials
> chore: use personal token for release-please

- .github/workflows/cd.yml
> chore: allow cd to trigger workflow

- .github/workflows/cd-manual.yml
**Motivation**
Quick option to manually deploy to cloudflare pages
> chore: manual deploy to cloudflare pages

- packages/ssz/src/util/strings.ts
fix: Remove replaceAll with replace(/.../g,... for ES2019 comptatibility
see:
- https://github.com/ethereumjs/ethereumjs-monorepo/issues/2554
> fix: Remove replaceAll with replace(/.../g,... for ES2019 compatibility

- packages/as-sha256/package.json
- packages/persistent-merkle-tree/package.json
- packages/persistent-merkle-tree/src/hasher/index.ts
- packages/persistent-merkle-tree/src/hasher/types.ts
- packages/persistent-merkle-tree/src/hasher/util.ts
- packages/persistent-merkle-tree/src/node.ts
- packages/ssz/src/branchNodeStruct.ts
- packages/ssz/src/util/merkleize.ts
- packages/ssz/src/util/zeros.ts
- setHasher.mjs
**Motivation**
The goal of this PR is to stop relying on `package.json` `exports`, as it may break older build tools such as Browserify.
Uses explicit imports for all imports that were previously using `exports` aliases.
> fix: Use file path imports

- packages/simpleserialize.com/package.json
- packages/simpleserialize.com/src/components/Footer.tsx
- packages/simpleserialize.com/src/components/Header.tsx
- packages/simpleserialize.com/src/components/Input.tsx
- packages/simpleserialize.com/src/types/index.ts
- packages/simpleserialize.com/src/util/types.ts
- packages/simpleserialize.com/webpack.config.js
- yarn.lock
**Motivation**
Closes https://github.com/ChainSafe/ssz/issues/320
- Add `capella` fork types
- Use `@lodestar/types` package instead of `@chainsafe/lodestar-types`
- Update consensus spec version to 1.3.0
- Set `capella` as default fork instead of `phase0`
- Add webpack config rules to fix build issues
> feat: support capella fork on simpleserialize.com

- packages/simpleserialize.com/src/components/Input.tsx
**Motivation**
Closes https://github.com/ChainSafe/ssz/issues/322
Easiest solution I found with high confidence of not breaking something.
It will now also show a error popup instead of just logging to console, the errors are quite technical and might not be that helpful sometimes but at least a user gets notified that something is not right.
> fix: show errors during serialization/deserialization as popup

- packages/simpleserialize.com/src/util/types.ts
**Motivation**
Closes https://github.com/ChainSafe/ssz/issues/326
Patch SSZ types to support full uint64 range on simpleserialize.com
> feat: support full uint64 range on simpleserialize.com

- packages/ssz/src/index.ts
- packages/ssz/src/type/bitList.ts
- packages/ssz/src/type/container.ts
**Motivation**
- We want `getFieldRanges` to be published so that we can load different chunks of data on demand in lodestar
- We also want to use `deserializeUint8ArrayBitListFromBytes` in lodestar https://github.com/ChainSafe/lodestar/blob/v1.11.1/packages/beacon-node/src/util/sszBytes.ts#L220
Publish the above methods in ssz
> feat: publish more methods

- packages/ssz/src/viewDU/listBasic.ts
- packages/ssz/test/unit/byType/listBasic/tree.test.ts
**Motivation**
- For lodestar, we may want to load beacon state ssz bytes to an existing `ViewDU` object, this is needed to optimize the process in case a field is rarely changed
- Add `sliceTo` method to ListBasicTreeViewDU, similar to https://github.com/ChainSafe/ssz/blob/d18ea08177544c82b9a1e7dd09127b4d63a2b2d8/packages/ssz/src/viewDU/listComposite.ts#L45
> feat: implement sliceTo() for ListBasicTreeViewDU

- .github/workflows/benchmark.yml
- .github/workflows/test.yml
- packages/ssz/src/value/bitArray.ts
**Motivation**
- Experimentation in lodestar
- `intersectValues` was needlessly strict, requiring an `Array` rather than something merely `ArrayLike`, like a `TypedArray`.
> fix: relax BitArray#intersectValues types

- .github/workflows/cd-manual.yml
- .github/workflows/cd.yml
**Motivation**
0.14.1 failed to publish https://github.com/ChainSafe/ssz/actions/runs/7852803588/job/21431695079#step:4:23
Move `corepack enable` step before `setup-node` step
> fix: fix ci

- packages/ssz/src/view/bitArray.ts
- packages/ssz/src/viewDU/bitArray.ts
**Motivation**
- follow up from #339 
- Relaxes other instances of `intersectValues`
> fix: relax other instances of intersectValues

- packages/ssz/src/index.ts
- packages/ssz/src/type/array.ts
- packages/ssz/src/type/composite.ts
- packages/ssz/src/type/listBasic.ts
- packages/ssz/src/type/listComposite.ts
- packages/ssz/src/util/merkleize.ts
need to cache merkle root of big lists (Transactions), as well as to allow setting the cached root (so needing cached symbol import) so that if we have for e.g. transactionsRoot, that can be set on transactions helping avoid merklelization of it in big blocks
> feat: add capability to cache merkle roots for lists

- packages/ssz/src/index.ts
- packages/ssz/src/type/arrayBasic.ts
- packages/ssz/src/type/arrayComposite.ts
- packages/ssz/src/type/container.ts
- packages/ssz/src/view/container.ts
- packages/ssz/src/viewDU/abstract.ts
- packages/ssz/src/viewDU/arrayComposite.ts
- packages/ssz/src/viewDU/container.ts
- packages/ssz/src/viewDU/listBasic.ts
- packages/ssz/src/viewDU/listComposite.ts
- packages/ssz/test/spec/runValidTest.ts
- packages/ssz/test/unit/byType/container/tree.test.ts
**Motivation**
- ViewDU has cached nodes, however when we serialize we go through the respective type and it loads all nodes again, see https://github.com/ChainSafe/ssz/blob/6220d320b004ea80bd30925487ac0f3299295528/packages/ssz/src/type/container.ts#L233
- This is to improve `state.serialize()` in lodestar: right after we get through state transition, we always have cached nodes inside
Define `serialize()` in ViewDU to go through the new `serializeToBytes()` method instead of its respective type class
- Add `serializeToBytes()` method to TreeViewDU, by default it'll delegate to respective type class
- The container ViewDU `serializeToBytes()` will recursively call respective `serializeToBytes` of internal ViewDU properties
- For `listComposite` and `listBasic` ViewDUs, …
> feat: improve ViewDU.serialize()

- packages/persistent-merkle-tree/src/packedNode.ts
- packages/persistent-merkle-tree/test/unit/packedNode.test.ts
- packages/ssz/src/type/listUintNum64.ts
- packages/ssz/test/lodestarTypes/phase0/sszTypes.ts
- packages/ssz/test/unit/byType/listBasic/tree.test.ts
**Motivation**
- Improve performance of `ListBasicType<UintNumberType<8>>.toViewDU()` (`balances` type in lodestar), the performance issue was noted here https://github.com/ChainSafe/ssz/blob/14c4457026a9fbea5bfe5c66580f7c8a8bee790a/packages/ssz/src/type/abstract.ts#L96
- Cache the created leaf nodes when calling that function and populate them to resulting ViewDU object, see https://github.com/ChainSafe/lodestar/issues/6520
- New `ListUintNum64Type` class and overwrite `toViewDU()` function:
- create nodes directly from `number[]` instead of having to `serialize()/deserialize()` implementation in the parent abstract class
- use the created LeftNodes to populate the final ViewDU object
part of https://github.com/ChainSafe/lodestar/issues/6520
> feat: new type for list of uint64

- packages/persistent-merkle-tree/README.md
- packages/ssz/src/index.ts
**Motivation**
- The release of ssz v0.15.0 and `persistent-merkle-tree` v0.7.0 were not successful with this CI so need to release new version  https://github.com/ChainSafe/ssz/actions/runs/8258360670/job/22590459475
- Fix ssz: export new `ListUintNum64Type` type from #352
- Modify persistent-merkle-tree readme in order to trigger new release
> fix: export ListUintNum64Type

- packages/simpleserialize.com/package.json
- packages/simpleserialize.com/src/components/Header.tsx
- packages/simpleserialize.com/src/components/Input.tsx
- packages/simpleserialize.com/src/util/types.ts
- yarn.lock
- Adding Deneb support to simpleserialize.com
- Set default fork to Deneb
- Bump `@lodestar/types` to `v1.14.0` to reflect the latest change of Deneb ssz type
> feat: Add deneb to simpleserialize.com

- packages/ssz/src/viewDU/listComposite.ts
- packages/ssz/test/unit/byType/listComposite/tree.test.ts
Add `sliceFrom` to `ListCompositeTreeViewDU`. 
Used in EIP-7251 to slice various beacon state fields like `pendingBalanceDeposit`, `pendingConsolidation` during epoch processing. 
Refer to the spec for more details:
[`process_pending_balance_deposits`](https://github.com/ethereum/consensus-specs/blob/f5207db2c415f676bb61d173031d1c233579f1a8/specs/_features/eip7251/beacon-chain.md?plain=1#L599)
[`process_pending_consolidations `](https://github.com/ethereum/consensus-specs/blob/f5207db2c415f676bb61d173031d1c233579f1a8/specs/_features/eip7251/beacon-chain.md?plain=1#L628)
[`process_withdrawals`](https://github.com/ethereum/consensus-specs/blob/f5207db2c415f676bb61d173031d1c233579f1a8/specs/_features/eip7251/beacon-chain.md?plain=1#L734)
> feat: add `sliceFrom` to `ListCompositeTreeViewDU`

- packages/ssz/src/value/bitArray.ts
`getSingleTrueBit()` does not throw on `ERROR_MORE_THAN_ONE_BIT_SET` nor `ERROR_NO_BIT_SET`, but returns null.
This PR updates the description to match the actual behaviour.
> fix: correct comment on BitArray.getSingleTrueBit

- .github/workflows/benchmark.yml
- .github/workflows/cd-manual.yml
- .github/workflows/cd.yml
- .github/workflows/test.yml
Use node20 and setup-node v4 in GitHub workflows as recommended [here](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/)
This should fix CI errors when attempting to run yarn using node16. See [error log](https://github.com/ChainSafe/ssz/actions/runs/8751637236/job/24030166543)
> chore: bump node version in GitHub workflows

- packages/persistent-merkle-tree/src/tree.ts
- packages/persistent-merkle-tree/test/unit/tree.test.ts
**Motivation**
The current `findDiffDepthi` only support up to 31 bits due to bit xor `^` limitation
Support > 32 bits numbers:
- Return early of number of bits between `index0` and `index1` are different
- If it's > 32 bits, separate to higher bits part and lower bits part by masking operation
Fix the 32 bits number:
- Fix `findDiffDepthi()` itself by handling non-positive `xor` result
Closes #370
Run all unit tests
> fix: findDiffDepthi to support more than 31 bytes

- packages/ssz/src/viewDU/abstract.ts
- packages/ssz/src/viewDU/arrayComposite.ts
- packages/ssz/src/viewDU/container.ts
- packages/ssz/test/unit/unchangedViewDUs.test.ts
**Motivation**
There are some read-only operations during state transition, for example: state.balances.length, state.validators.length, state.latestBlockHeaders
although the data is not changed, ViewDU still track it as changed node and blindly rebind nodes, which takes time to rebind and compute roots
- compare to the current tracked nodes before doing the update, this is for composite-type related super type
Closes #379
> fix: do not rebind nodes if child ViewDU is not changed

- packages/ssz/src/viewDU/arrayComposite.ts
- packages/ssz/src/viewDU/container.ts
**Motivation**
resolve this `TODO` https://github.com/ChainSafe/ssz/blob/3a1c8dc54a571dfed4cc426810472627b334e9b9/packages/ssz/src/viewDU/container.ts#L94
- sort changed nodes before the loop
- this branch
- `te/batch_hash_tree_root`
> fix: optimize commit() for Container and ArrayComposite ViewDUs

- packages/ssz/src/view/arrayBasic.ts
- packages/ssz/src/view/arrayComposite.ts
- packages/ssz/src/viewDU/arrayBasic.ts
- packages/ssz/src/viewDU/arrayComposite.ts
**Motivation**
- In some state transition flows of lodestar, the returned value of `getAll()` or `getAllReadonly()` or `getAllReadonValues()` are just temporary objects, we can preallocate them at the file level and reuse to save gc time
- Add an optional array input to `getAll*()` apis, consumers can decide to use them or not
- lodestar will reuse arrays in its state transition functions similar to the strategy in https://github.com/ChainSafe/lodestar/pull/6945
> feat: support optional output arrays for getAll() apis

- packages/as-sha256/src/hashObject.ts
- packages/as-sha256/src/index.ts
- packages/as-sha256/test/perf/index.test.ts
- packages/as-sha256/test/perf/simd.test.ts
- packages/as-sha256/test/unit/index.test.ts
- packages/as-sha256/test/unit/simd.test.ts
- packages/persistent-merkle-tree/src/hasher/util.ts
- packages/persistent-merkle-tree/test/unit/tree.test.ts
**Motivation**
The hashInto() api of hashtree is very efficient in terms of memory allocation for the consumer because they can preallocate output and reuse over multiple hashes, they can also hash into the same input Uint8Array
- implement hashInto() api with the same interface to hashtree
- implement `digest64HashObjectsInto()` which is similar to `digest64HashObjects()` but this does not allocate new HashObject
- implement `byteArrayIntoHashObject()` which is similar to `byteArrayToHashObject()`, but this does not allocate new HashObject
all of these functions are used by `persistent-merkle-tree` and `ssz` in upcoming PRs
**BREAKING CHANGE**
- add `offset` param to `byteArrayToHashObject()` so that consumer can use the same big Uint8Array to extract HashObject from a …
> feat!: implement hashInto() api for as-sha256

- packages/persistent-merkle-tree/src/hashComputation.ts
- packages/ssz/src/index.ts
- packages/ssz/src/interface.ts
- packages/ssz/src/util/reusableListIterator.ts
- packages/ssz/src/view/arrayComposite.ts
- packages/ssz/src/viewDU/arrayComposite.ts
- packages/ssz/test/perf/byType/listComposite.test.ts
- packages/ssz/test/perf/iterate.test.ts
- packages/ssz/test/perf/util/reusableListIterator.test.ts
- packages/ssz/test/unit/byType/listComposite/tree.test.ts
- packages/ssz/test/unit/util/reusableListIterator.test.ts
**Motivation**
- avoid possible array allocation with getAll() api
#383 make it possible to provide an Array for getAll() api, however it could still spike due to array allocation
- Implement ReusableListIterator which is a LinkedList, when it grows it only append some more items instead of allocating a big array
- Implement getAll*Iter()  api to View and ViewDU to allow consumer to use `ReusableListIterator`
- On average, ReusableListIterator is only a bit faster than Array however the key thing is to reduce any spikes as much as possible due to gc
**Testing**
- This branch (lg1k) in the last 24h, 10m rate interval, there are ~3 spikes
- `te/batch_hash_tree_root`, md64, 10m rate interval, there are ~18 spikes
- This branch (lg1k) in the last 24h, 12h rate interval. It's …
> feat: ReuseListIterator for getAll() api

- packages/ssz/src/branchNodeStruct.ts
- packages/ssz/src/type/containerNodeStruct.ts
- packages/ssz/src/view/containerNodeStruct.ts
- packages/ssz/test/lodestarTypes/phase0/viewDU/listValidator.ts
- packages/ssz/test/perf/eth2/beaconState.test.ts
**Motivation**
Don't want to modify `hashTreeRoot()` in any ways
- ListValidatorTreeViewDU: return `super.commit()` if it's from `hashTreeRoot()`
- Revert `BranchNodeStruct` because we compute and apply validator roots in ListValidatorTreeViewDU for `batchHashTreeRoot()` flow
- Update to the original benchmark to make sure there is no performance regression
```
BeaconState ViewDU partially modified tree vc=200000 numModified=100000
✓ BeaconState ViewDU batchHashTreeRoot vc=200000                      7.316355 ops/s    136.6801 ms/op        -         85 runs   20.4 s
✓ BeaconState ViewDU batchHashTreeRoot - commit step vc=200000        8.522365 ops/s    117.3383 ms/op        -        101 runs   20.3 s
✓ BeaconState ViewDU batchHashTreeRoot - hash step vc=200000 …
```
> fix: do not change hashTreeRoot()

- packages/ssz/src/viewDU/listComposite.ts
- packages/ssz/test/unit/byType/listComposite/tree.test.ts
**Motivation**
- sliceFrom() api was implemented with the assumption that `this.nodes` are fully populated but it's not unless `populateAllNodes()` is called
- reproduce the bug in unit test
- call `populateAllNodes()` api to fix it
> fix: sliceFrom api

- packages/ssz/test/lodestarTypes/phase0/viewDU/listValidator.ts
- packages/ssz/test/perf/eth2/beaconState.test.ts
**Motivation**
Some `validators.get(i)` may call and it's tracked in `viewsChanged`, right now we compute its root in batch while we should not
- commit all validators first
- filter out those have roots already
- update benchmark to test it
**Benchmark**
with half of `validators.get()` called without modifying anything
- current
```
BeaconState ViewDU partially modified tree vc=200000 numModified=100000
✓ BeaconState ViewDU batchHashTreeRoot vc=200000                      3.311916 ops/s    301.9400 ms/op        -         40 runs   20.7 s
✓ BeaconState ViewDU batchHashTreeRoot - commit step vc=200000        3.735825 ops/s    267.6785 ms/op        -         50 runs   20.5 s
✓ BeaconState ViewDU batchHashTreeRoot - hash step vc=200000          21.26964 ops/s    47.01538 …
```
> fix: handle unmodified validators

- packages/as-sha256/package.json
**Motivation**
The npm page for this module has out of date links.
The [npm page](https://www.npmjs.com/package/@chainsafe/as-sha256) for this module has links to a long-archived repo so update the bugs/issues/etc links in the manifest to give a bit of traceability.
n/a
> fix: add homepage/repo etc to as-sha256 package.json

- packages/persistent-merkle-tree/src/packedNode.ts
- packages/ssz/src/index.ts
- packages/ssz/src/type/listUintNum64.ts
- packages/ssz/test/perf/byType/listUintNum64.test.ts
- packages/ssz/test/unit/byType/listBasic/listUintNum64.test.ts
**Motivation**
- In lodestar, at every epoch transition we create a new balances tree using `ListUintNum64Type.toViewDU()` api. This PR add an optional `unusedViewDU` to that api which helps reuse balances tree and avoid memory allocation in lodestar
- This PR is technically not related to batch hash work, however using `executeHashComputation()` is a great way to rehash the whole tree
- The implementation is very similar to pushing new values to an existing ViewDU, then `commit()`
- Unit test and perf test are added. Although perf test does not show a great improvement, memory would be saved a lot.
> feat: ListUintNum64Type create ViewDU from existing tree

- .github/workflows/cd.yml
**Motivation**
Fix the lerna command for publishing the packages. 
During the downgrading of the `yarn` https://github.com/ChainSafe/ssz/pull/374 the command was broken. 
Closes https://github.com/ChainSafe/ssz/issues/396
- Merge the PR and run the CD pipeline
> fix: lerna command for publishing packages

- packages/ssz/src/index.ts
- packages/ssz/src/util/upgrade.ts
- packages/ssz/test/unit/byType/container/tree.test.ts
**Motivation**
Cannot reuse an existing tree when upgrading to new type, see https://github.com/ChainSafe/lodestar/issues/6811
- new "upgradeToNewType" api as discussed [Lodestar#6811](https://github.com/ChainSafe/lodestar/issues/6811#issuecomment-2129571320)
- usage:
```typescript
const newType = new ContainerType(newFields);
const newView = newType.getView(new Tree(view.upgradeToNewType(newType)));
const newViewDU = newType.getViewDU(viewDU.upgradeToNewType(newType));
```
> feat: new api to upgrade a tree to new type

- .github/workflows/cd.yml
**Motivation**
Fix the publish script for the workflow. 
In previous https://github.com/ChainSafe/ssz/pull/408 I left out `--tolerate-republish` as it was used for a very long time. 
https://github.com/ChainSafe/ssz/blob/18baeaa7b47fcda67bdba8380cbf430827e1eb3d/.github/workflows/cd.yml#L58
But actual issue was mixing up `npm publish` with the `yarn npm publish`. So eventually `yarn` had it's own set of npm commands. 🥹 
https://yarnpkg.com/cli/npm/publish
- Run all tests and publish a newer version later on.
> fix: update the publish script to use only npm options

- packages/persistent-merkle-tree/src/hasher/as-sha256.ts
- packages/persistent-merkle-tree/src/hasher/hashtree.ts
- packages/persistent-merkle-tree/src/hasher/index.ts
- packages/persistent-merkle-tree/src/hasher/noble.ts
- packages/persistent-merkle-tree/src/hasher/types.ts
- packages/persistent-merkle-tree/src/hasher/util.ts
- packages/persistent-merkle-tree/test/unit/hasher.test.ts
- packages/ssz/src/type/arrayComposite.ts
- packages/ssz/src/type/bitArray.ts
- packages/ssz/src/type/bitList.ts
- packages/ssz/src/type/byteArray.ts
- packages/ssz/src/type/byteList.ts
- packages/ssz/src/type/container.ts
- packages/ssz/src/type/listBasic.ts
- packages/ssz/src/type/listComposite.ts
- packages/ssz/src/type/optional.ts
- packages/ssz/src/type/profile.ts
- packages/ssz/src/type/stableContainer.ts
- packages/ssz/src/type/union.ts
- packages/ssz/src/type/vectorBasic.ts
- packages/ssz/src/type/vectorComposite.ts
- packages/ssz/test/perf/merkleize.test.ts
- packages/ssz/test/unit/byType/byteList/value.test.ts
- packages/ssz/test/unit/byType/container/tree.test.ts
- packages/ssz/test/unit/byType/listComposite/tree.test.ts
- packages/ssz/test/unit/merkleize.test.ts
**Motivation**
- When we have a list of bytes or list of composite, if new value is over the cached chunk/block bytes, right now we reallocate the whole Uint8Array which is not good due to gc
- Instead of that, implement `merkleizeBlockArray(blocks: Uint8Array[], ...)`. In the above case we only need to allocate some more Uint8Array instances, each 64 bytes
- refactor `merkleizeInto()` to `merkleizeBlocksBytes()` to avoid naming conflict
- model block bytes which is 64 bytes instead of chunk bytes which is 32 bytes
- this branch run on `feat` `16, 1, novc` for 5 days without issue
- persisting `gc` statistic on 1d interval of `md16`:
- vs stable md16
> feat: merkleize block array

- packages/persistent-merkle-tree/src/hasher/as-sha256.ts
- packages/persistent-merkle-tree/src/hasher/hashtree.ts
- packages/persistent-merkle-tree/src/hasher/index.ts
- packages/persistent-merkle-tree/src/hasher/noble.ts
- packages/persistent-merkle-tree/src/hasher/types.ts
- packages/persistent-merkle-tree/src/hasher/util.ts
- packages/persistent-merkle-tree/test/unit/hasher.test.ts
**Motivation**
- when we have a list of bytes or list of composite, if new value is over the cached chunk/block bytes, right now we reallocate the whole Uint8Array which is not good for gc
- Instead of that, implement `merkleizeBlockArray(blocks: Uint8Array[], ...)`. In the above case we only need to allocate some more Uint8Array instances, each 64 bytes
- refactor `merkleizeInto()`:
- rename `merkleizeBlocksBytes()` to avoid naming conflict
- rename variables
- model block bytes which is 64 bytes instead of chunk bytes which is 32 bytes (1 block = 2 chunks)
- the consuming of this `merkleizeBlockArray()` method will come in the next PR
part of #378
> feat: implement merkleizeBlockArray

- packages/simpleserialize.com/package.json
- packages/simpleserialize.com/src/util/types.ts
- yarn.lock
- Adding Electra (as of `v1.5.0-alpha.8`) support to simpleserialize.com
Deneb will remain as default fork as Electra is not live yet.
> feat: add electra to simpleserialize.com

- release-please-config.json
**Motivation**
Testing to see if this fixes deployment issues
> chore: remove release-as versions in config

- setHasher.mjs
**Motivation**
Use the `hashtree` hasher for the benchmarks.
- During the PR https://github.com/ChainSafe/ssz/pull/426/ the hasher was changed for the benchmarks 
- We have `main` field in `package.json` pointed to the `lib/cjs/index.js` folder and `module` field pointed to `lib/index.js`. 
- It seems that in TS it's by default loading up the `main` instead of `module` for package import. 
- So we have to set proper hasher for the benchmarks. 
- Run all tests
**Reference**
https://www.typescriptlang.org/docs/handbook/modules/reference.html#packagejson-main-and-types
> fix: update the hasher for benchmarks

- packages/persistent-ts/package.json
- packages/ssz/package.json
**Motivation**
Support both `cjs` and `esm` builds.
- Fix the files to include in the package`
- Run all tests
> fix: publish nested package.json files in the lib

- .release-please-manifest.json
- packages/as-sha256/CHANGELOG.md
- packages/as-sha256/package.json
- packages/persistent-merkle-tree/CHANGELOG.md
- packages/persistent-merkle-tree/package.json
- packages/persistent-ts/CHANGELOG.md
- packages/persistent-ts/package.json
- packages/ssz/CHANGELOG.md
- packages/ssz/package.json
- release-please-config.json
**Motivation**
Because `relase-please` is a flaming dumpster fire.... heavy sigh
- reverts commit that did not trigger correct release
> chore: revert invalid release commit and create valid commit triggers

- .github/workflows/release.yml
**Motivation**
CD is broken because the token is not written to the correct location.  Update the workflow to echo the npm token to `.npmrc` and renames workflow to `release` instead of `cd` because that is the only job in the file
> chore: update CD publish step to add token to .npmrc

- .github/workflows/release.yml
Use `npm config set` command to add creds using command to it resolves correctly and then ditch yarn calling lerna and call lerna directly.
> fix(as-sha256, persistent-ts): update workflow to revise publish process

- packages/persistent-merkle-tree/package.json
- setHasher.mjs
**Motivation**
Allow users to easily choose the hasher. 
- Use named exports for different hashers 
- Limit users to not load build directories directly
Run all tests
> feat!: use named exports to expose different hashers

- .github/workflows/release.yml
Update npm publish to how it was "before" yarn 3 migration - see https://github.com/ChainSafe/ssz/pull/290/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L17
> fix: update npm publish step

- packages/ssz/src/viewDU/arrayComposite.ts
- packages/ssz/test/unit/byType/listComposite/tree.test.ts
**Motivation**
got `Must commit changes before reading all nodes` error in devnet-5 of electra https://github.com/ChainSafe/lodestar/pull/7375
- getAllReadonly() without commit
- we should be able to populate nodes array up until the old length
- then get from the pending change, if not then get from the ViewDU of loaded `this.nodes`
- getAllReadonlyValues() still need the commit change because we want the nodes of pending changes. So although the name is similar, it's different from `getllReadonly()`
- unit test was added
cc @nflaig @wemeetagain
> fix: ListCompositeTreeViewDU to getAllReadonly() without commit

- packages/ssz/src/view/arrayBasic.ts
- packages/ssz/src/view/arrayComposite.ts
- packages/ssz/src/viewDU/arrayBasic.ts
- packages/ssz/src/viewDU/arrayComposite.ts
- packages/ssz/test/unit/byType/listComposite/tree.test.ts
**Motivation**
- avoid memory allocation when consumer want to loop through all item of a ListComposite
- new `forEach() & forEachValue()` api: no memory allocation for array needed
- optional "out" param for getAll() apis so that consumer can allocate memory once and reuse if they want to
cherry-picked from #417
> feat: forEach() api for ArrayComposite()

- packages/ssz/src/viewDU/arrayComposite.ts
- packages/ssz/src/viewDU/container.ts
- packages/ssz/test/unit/unchangedViewDUs.test.ts
**Motivation**
- some child ViewDUs are not changed for read-only operations, however parent still rebind it, see #379
- do not rebind in that case. This applies for Container and ArrayComposite
- this was cherry-picked from #417 to make it easier to review
Closes #379
> fix: do not rebind node if unchanged child ViewDUs

- packages/ssz/src/viewDU/arrayComposite.ts
- packages/ssz/test/unit/byType/listComposite/tree.test.ts
**Motivation**
- when the list length is big, application may want to get by chunk instead of get all of items because logic may break in the middle and using `getAllReadonly()` is not performant
see https://github.com/ChainSafe/lodestar/issues/7565
- implement `getReadonlyByRange()` api
- unit test added
> feat: get list composite by range

- packages/ssz/src/index.ts
- packages/ssz/test/lodestarTypes/phase0/listValidator.ts
- packages/ssz/test/lodestarTypes/phase0/sszTypes.ts
- packages/ssz/test/lodestarTypes/phase0/validator.ts
- packages/ssz/test/lodestarTypes/phase0/viewDU/listValidator.ts
- packages/ssz/test/perf/eth2/beaconState.test.ts
- packages/ssz/test/perf/eth2/hashTreeRoot.test.ts
- packages/ssz/test/perf/eth2/validators.test.ts
- packages/ssz/test/unit/lodestarTypes/phase0/listValidator.test.ts
- packages/ssz/test/unit/lodestarTypes/phase0/validator.test.ts
- packages/ssz/test/unit/merkleize.test.ts
**Motivation**
- model ListValidator ssz type, it's technically for lodestar. However we want to track its performance here
- export necessary types so lodestar can use
- also bring remaining tests from #378
> feat: model ListValidator ssz type

- biome.jsonc
- packages/persistent-merkle-tree/src/gindex.ts
- packages/persistent-merkle-tree/src/node.ts
- packages/persistent-merkle-tree/src/proof/compactMulti.ts
- packages/persistent-merkle-tree/src/proof/treeOffset.ts
- packages/persistent-merkle-tree/src/proof/util.ts
- packages/persistent-merkle-tree/src/subtree.ts
- packages/persistent-merkle-tree/src/tree.ts
- packages/persistent-ts/src/Vector.ts
- packages/simpleserialize.com/src/components/TreeView.tsx
- packages/simpleserialize.com/src/util/partials.ts
- packages/ssz/src/type/arrayBasic.ts
- packages/ssz/src/type/arrayComposite.ts
- packages/ssz/src/type/bitList.ts
- packages/ssz/src/type/container.ts
- packages/ssz/src/type/optional.ts
- packages/ssz/src/type/profile.ts
- packages/ssz/src/type/stableContainer.ts
- packages/ssz/src/type/uint.ts
- packages/ssz/src/util/proof/treePartialToJsonPaths.ts
- packages/ssz/src/util/proof/treePostProcessFromProofNode.ts
- packages/ssz/src/value/bitArray.ts
- packages/ssz/src/viewDU/abstract.ts
- packages/ssz/src/viewDU/partialListComposite.ts
- packages/ssz/test/perf/misc/switch_if_cost.test.ts
- packages/ssz/test/spec/replaceUintTypeWithUintBigintType.ts
- packages/ssz/test/spec/runValidTest.ts
> chore: fix linting rule lint/style/noUselessElse
