ChainSafe/ssz

src/util/merkleize.ts, src/util/zeros.ts
=> Reuse arraybuffer memory in buffer conversion

src/backings/structural/vector.ts, test/unit/regression.test.ts
=> Fix composite vector defaultValue

package.json, yarn.lock
See https://github.com/ChainSafe/persistent-merkle-tree/pull/8
=> Update persistent-merkle-tree dep

src/backings/structural/abstract.ts, src/backings/structural/array.ts, src/backings/structural/bitList.ts, src/backings/structural/bitVector.ts, src/backings/structural/byteVector.ts, src/backings/structural/container.ts, src/backings/structural/list.ts, src/backings/structural/vector.ts, src/types/basic/abstract.ts, src/types/composite/abstract.ts
=> Implement minSize and maxSize api

src/backings/structural/abstract.ts, src/backings/structural/array.ts, src/backings/structural/bitList.ts, src/backings/structural/bitVector.ts, src/backings/structural/byteVector.ts, src/backings/structural/container.ts, src/backings/structural/list.ts, src/backings/structural/vector.ts, src/types/basic/abstract.ts, src/types/basic/boolean.ts, src/types/basic/uint.ts, test/unit/deserialize.test.ts, test/unit/objects.ts
=> Validation for fromBytes

src/backings/structural/array.ts
=> Add length check to array structural equality

src/backings/byteArray/abstract.ts
As per @dapplion suggestion, resolves #63
=> Optimize byte array equals

.eslintrc.js, src/backings/byteArray/array.ts, src/backings/structural/array.ts
See https://lgtm.com/projects/g/ChainSafe/ssz/alerts/?mode=list
=> Fix lgtm alerts

package.json, src/backings/tree/abstract.ts, src/backings/tree/array.ts, src/backings/tree/container.ts, yarn.lock
Depends on chainsafe/persistent-merkle-tree#21 and subsequent release
=> Initial multiproof support

src/types/composite/bitList.ts, src/types/composite/bitVector.ts, test/unit/regression.test.ts
=> Fix bit array struct->tree

src/backings/tree/treeValue.ts, src/types/basic/boolean.ts, src/types/basic/uint.ts, src/types/composite/abstract.ts, src/types/composite/array.ts, src/types/composite/bitList.ts, src/types/composite/bitVector.ts, src/types/composite/byteVector.ts, src/types/composite/container.ts, src/types/composite/list.ts, src/types/composite/root.ts, src/types/composite/vector.ts, src/util/byteArray.ts, test/unit/tree.test.ts
=> Add whitespace

src/types/composite/container.ts, src/types/composite/list.ts
See https://github.com/ChainSafe/lodestar/pull/1845
=> Use for of instead of forEach

src/types/composite/vector.ts, test/unit/regression.test.ts
Fix a recursive loop. `fromJson` calls `struct_convertFromJson` (which should not call `fromJson`)
Add regression test
=> Fix basic vector struct_convertFromJson

src/types/composite/root.ts
See chainsafe/lodestar#2708
Add a fast path for RootType equality
Since root types are known to be 32 bytes, we can tighten down the implementation in several ways:
- Replace the slower `ArrayType#struct_equals` with a `byteArrayEquals` impl
- Use `value.tree.root` to get the Uint8Array for tree-backed values
- Replace the more generic, slower `AbstractType#equals` with the fast `RootType#struct_equals`
=> Add fast struct_equals impl for RootType

src/types/basic/uint.ts
=> Use utility function for bigint exponentiation

package.json, yarn.lock
+ persistent-merkle-tree 0.3.5
+ as-sha256 0.2.4
=> Use persistent-merkle-tree 0.3.5

.github/workflows/benchmark.yml
@wemeetagain Please add secrets when possible
=> Update benchmark script

.github/workflows/benchmark.yml, .mocharc.yaml, package.json, test/perf/iterate.test.ts, test/perf/list.test.ts, test/perf/propertyGet.test.ts, test/perf/serdes.test.ts, test/perf/uint.test.ts, test/perf/validators.test.ts, yarn.lock
**Motivation**
Prevent OOM and better stability
Bump @dapplion/benchmark to v0.2.2
=> Bump @dapplion/benchmark to v0.2.2

.github/workflows/release.yml, packages/ssz/CHANGELOG.md, packages/ssz/package.json
- Ability to specify casingMap declaration time for Container's toJson/fromJson [#198](https://github.com/ChainSafe/ssz/pull/198)
- Extending case matching in Container's toJson/fromJson with a range of case types [#184](https://github.com/ChainSafe/ssz/pull/184)
- Ability to provide casingMap in toJson/fromJson interface for aiding case matching [#184](https://github.com/ChainSafe/ssz/pull/184)
=> ssz version 0.8.18 release

packages/ssz/test/unit/deserialize.test.ts
**Motivation**
Demonstrate the type inference of UnionType
Write unit test for it
=> New unit test to demo type inference for UnionType

packages/persistent-ts/test/unit/Vector.test.ts, packages/ssz/src/types/basic/uint.ts, packages/ssz/src/types/composite/bitList.ts, packages/ssz/src/types/composite/list.ts, packages/ssz/test/spec/generic/index.test.ts, packages/ssz/test/unit/regression.test.ts
**Motivation**
chai `.to.throw` is a function, if not called the assertion has no effect.
chai `.to.throw` assertion
**TODO**
=> Call throw assertion

packages/ssz/test/perf/deserializationEth2.test.ts, packages/ssz/test/perf/serdes.test.ts, packages/ssz/test/perf/validators.test.ts, packages/ssz/test/utils/generateEth2Objs.ts
**Motivation**
Add important benchmarks to test against https://github.com/ChainSafe/ssz/pull/223
Add more benchmarks for:
- Full eth2 state (de)serialization
- More eth2 data structures
=> Add more benchmarks

packages/simpleserialize.com/package.json, packages/simpleserialize.com/src/components/Header.tsx, packages/simpleserialize.com/src/util/types.ts, yarn.lock
**Motivation**
We want simpleserialize.com to have bellatrix types
Add bellatrix types
Update header to remove "eth2" and update spec version
=> Update simpleserialize.com w bellatrix types

packages/as-sha256/CHANGELOG.md, packages/as-sha256/package.json, packages/persistent-merkle-tree/CHANGELOG.md, packages/persistent-merkle-tree/package.json, packages/ssz/CHANGELOG.md, packages/ssz/package.json
**Motivation**
Publish: `@chainsafe/ssz@0.9.1, @chainsafe/persistent-merkle-tree@0.4.1, @chainsafe/as-sha256@0.3.1`
=> chore: publish

packages/simpleserialize.com/src/components/ForkMe.tsx
Update link to repo in fork-me banner
=> Update link to repo in fork-me banner

.github/FUNDING.yml, packages/persistent-merkle-tree/test/unit/proof/util.test.ts, packages/simpleserialize.com/README.md, packages/simpleserialize.com/src/components/Footer.tsx, packages/ssz/test/spec/testRunner.ts
Minor updates to docs and links. No code modifications.
=> Docs and links update

packages/persistent-merkle-tree/CHANGELOG.md, packages/persistent-merkle-tree/package.json, packages/ssz/CHANGELOG.md, packages/ssz/package.json
**Motivation**
+ Release persistent-merkle-tree 0.4.2
+ Release ssz 0.9.2
=> Release ssz 0.9.2

.github/workflows/cf-deploy.yaml
**Motivation**
This change deploys the ssz repository to Cloudflare pages.
=> Deploy ssz repository to Cloudflare pages

packages/persistent-merkle-tree/package.json, packages/simpleserialize.com/package.json, packages/ssz/package.json, release-please-config.json, yarn.lock
=> chore: fix release-please

.github/workflows/cd.yml
=> chore: commit updated lockfile post release-please

.github/workflows/cd-manual.yml
=> chore: fix cloudflare pages build

packages/ssz/src/index.ts, packages/ssz/src/type/optional.ts, packages/ssz/test/unit/byType/optional/invalid.test.ts, packages/ssz/test/unit/byType/optional/tree.test.ts, packages/ssz/test/unit/byType/optional/valid.test.ts, packages/ssz/test/unit/byType/runTypeProofTest.ts
implement PR:
- [eip-6475](https://eips.ethereum.org/EIPS/eip-6475)
requirement to build verkle types as the kaustenine network (and its relaunch will use optional types)
=> feat: add optional ssz type

packages/ssz/src/viewDU/arrayComposite.ts, packages/ssz/test/unit/byType/listComposite/tree.test.ts
**Motivation**
- port #472 forward
- #472
=> feat: get list composite by range (#472)

biome.jsonc, packages/simpleserialize.com/src/App.tsx, packages/simpleserialize.com/src/components/Header.tsx, packages/simpleserialize.com/src/components/Input.tsx, packages/simpleserialize.com/src/components/Output.tsx, packages/simpleserialize.com/src/components/Serialize.tsx, packages/simpleserialize.com/src/components/TreeView.tsx, packages/simpleserialize.com/src/index.tsx
**Motivation**
Apply biomejs rules across all the codebase
- Fix all tsx files
- Run all tests
=> chore: fix all react files for linting rules
